# Generated by Django 5.0 on 2023-12-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwithdealership',
            name='dealerships',
            field=models.ManyToManyField(to='store.dealership'),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='cars',
            field=models.ManyToManyField(related_name='dealerships', to='store.car'),
        ),
    ]
