# Generated by Django 5.0.1 on 2024-01-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='phone',
            new_name='phone1',
        ),
    ]
