# Generated by Django 4.2.7 on 2023-11-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='descripion',
            new_name='descriptioin',
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_year',
            field=models.IntegerField(choices=[('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')]),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
