# Generated by Django 5.0.1 on 2024-01-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_phone_dealer_phone1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carowner',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='phone1',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='dealership',
            old_name='phone',
            new_name='contact',
        ),
    ]
