# Generated by Django 5.0 on 2023-12-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_carwithownership_carownership_cardealership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardealership',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_dealership', to='store.car'),
        ),
        migrations.AlterField(
            model_name='carownership',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_ownership', to='store.car'),
        ),
    ]
