# Generated by Django 5.1.6 on 2025-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_car_registration_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
