# Generated by Django 5.0.1 on 2024-01-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_phone_carowner_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
