# Generated by Django 4.2.7 on 2023-11-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_car_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='since',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(),
        ),
    ]
