# Generated by Django 5.0 on 2023-12-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cardealership_car_alter_carownership_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarDealerShip',
        ),
    ]
