# Generated by Django 5.1.6 on 2025-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_carowner_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=10),
        ),
    ]
