# Generated by Django 5.0.1 on 2024-01-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ratings',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=3, max_length=5),
            preserve_default=False,
        ),
    ]
