# Generated by Django 5.1.6 on 2025-03-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_carowner_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='carowner',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='carownership',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='dealership',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
    ]
