# Generated by Django 4.2.7 on 2023-11-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_company_since_alter_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ratings',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
