# Generated by Django 5.0 on 2024-01-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_cardealership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealership',
            name='cars',
        ),
        migrations.AddField(
            model_name='car',
            name='dealerships',
            field=models.ManyToManyField(related_name='cars_at_dealership', to='store.dealership'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='featured_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_at_dealership', to='store.car'),
        ),
    ]
