# Generated by Django 5.1.6 on 2025-03-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_car_options_alter_carowner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='dial_code',
            field=models.IntegerField(default=91),
        ),
        migrations.AddField(
            model_name='customer',
            name='dial_code',
            field=models.IntegerField(default=91),
        ),
        migrations.AddField(
            model_name='dealership',
            name='dial_code',
            field=models.IntegerField(default=91),
        ),
    ]
