# Generated by Django 5.1.6 on 2025-03-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_car_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='profile_pic',
            field=models.ImageField(upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company_logos/'),
        ),
    ]
