# Generated by Django 4.2.7 on 2023-11-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_car_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ratings',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
