# Generated by Django 5.1.6 on 2025-03-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_contact_carowner_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='balance',
            field=models.BigIntegerField(default=1000000.0),
        ),
    ]
