# Generated by Django 4.2.7 on 2023-11-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='discriptioin',
            new_name='descriptioin',
        ),
    ]
