# Generated by Django 4.2.5 on 2023-11-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_carowner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='lastname',
        ),
    ]
