# Generated by Django 4.2.11 on 2025-03-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_chatmessage_options_alter_chatmessage_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='personal_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='personal_address',
        ),
    ]
