# Generated by Django 4.2.5 on 2023-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration_year',
            field=models.CharField(choices=[('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=50),
        ),
    ]
