# Generated by Django 5.1.6 on 2025-03-30 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_customer_profile_pic_alter_carowner_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
