# Generated by Django 4.2.5 on 2023-11-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_customer_email_remove_customer_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
