# Generated by Django 4.2.7 on 2023-11-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_price_car_origenal_price_car_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='origenal_price',
        ),
    ]
