# Generated by Django 4.2.7 on 2023-11-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rename_selling_price_car_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
