# Generated by Django 4.2.7 on 2023-11-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_carowner_phone_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='car_owned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carowner', to='store.car'),
            preserve_default=False,
        ),
    ]
