# Generated by Django 4.2.7 on 2023-11-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_car_owned_carowner_carowned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='carowned',
        ),
        migrations.AddField(
            model_name='car',
            name='carowner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carowned', to='store.carowner'),
            preserve_default=False,
        ),
    ]
