# Generated by Django 4.2.7 on 2023-11-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_carowner_carowned_car_carowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carowneD',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
    ]
