# Generated by Django 4.2.7 on 2023-11-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_car_carowned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carowneD',
            new_name='carowned_id',
        ),
    ]
