# Generated by Django 4.2.7 on 2023-11-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_rename_carowned_car_carowned_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='carowned_id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='carowner',
        ),
    ]
