# Generated by Django 4.2.7 on 2023-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_car_carowned_id_remove_car_carowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carowned_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
