# Generated by Django 4.2.7 on 2023-12-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_car_carowned_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='address',
            new_name='bussiness_address',
        ),
        migrations.AddField(
            model_name='dealer',
            name='personal_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='store.company'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ratings',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
    ]
