# Generated by Django 4.2.7 on 2023-12-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_rename_address_dealer_bussiness_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='bussiness_address',
            new_name='address',
        ),
    ]
