# Generated by Django 4.2.7 on 2023-12-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_rename_bussiness_address_dealer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_owned', to='store.carowner'),
        ),
    ]
