# Generated by Django 4.2.7 on 2023-12-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_car_carowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='car_owned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='store.car'),
            preserve_default=False,
        ),
    ]
