# Generated by Django 4.2.7 on 2023-12-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_dealer_car_owned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='car_owned',
        ),
    ]
