# Generated by Django 4.2.7 on 2023-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_remove_dealer_car_owned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='original_price',
        ),
        migrations.AddField(
            model_name='dealer',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
