# Generated by Django 4.2.7 on 2023-12-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_remove_car_original_price_dealer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
    ]
