# Generated by Django 4.2.7 on 2023-12-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_car_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
