# Generated by Django 4.2.7 on 2023-12-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_remove_car_carowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owned_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carowned', to='store.carowner'),
            preserve_default=False,
        ),
    ]
