# Generated by Django 4.2.7 on 2023-12-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_car_owned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='price',
        ),
    ]
