# Generated by Django 4.2.7 on 2023-12-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_remove_dealer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_owned', to='store.carowner'),
        ),
    ]
