# Generated by Django 4.2.7 on 2023-12-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_car_owned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_owned', to='store.carowner'),
        ),
    ]
