# Generated by Django 4.2.7 on 2023-12-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0046_alter_car_owned_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.dealer')),
            ],
        ),
    ]
