# Generated by Django 5.0 on 2023-12-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_dealership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealership',
            old_name='dealer',
            new_name='dealership',
        ),
    ]
