# Generated by Django 5.0 on 2023-12-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_rename_dealer_dealership_dealership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealership',
            old_name='dealership',
            new_name='dealership_for_car',
        ),
    ]
