# Generated by Django 5.0 on 2023-12-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_rename_dealership_dealership_dealership_for_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealership',
            old_name='dealership_for_car',
            new_name='dealership_name',
        ),
    ]
