# Generated by Django 5.0 on 2023-12-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_remove_dealer_address_remove_dealer_dealership_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='phone',
            field=models.BigIntegerField(default=123123),
            preserve_default=False,
        ),
    ]
