# Generated by Django 5.0 on 2023-12-06 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_dealershipfor_dealership'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwithdealership',
            name='dealership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.dealership'),
            preserve_default=False,
        ),
    ]
