# Generated by Django 5.0 on 2023-12-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_carwithdealership_dealership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwithdealership',
            name='dealership',
        ),
    ]
